### ISSUE TITLE
Factory Method

### ISSUE THREAD

**Issue by matt-izatt** [matt-izatt/learn-design-patterns#13]
## Description
Factory Method is a creational design pattern that provides an interface for creating objects in a superclass, but allows subclasses to alter the type of objects that will be created.

## Link
https://refactoring.guru/design-patterns/factory-method

## Todo
- [x]  Create typescript example
- [ ]  Create class diagram
- [ ]  Create wiki page
